apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: prof-cont
          image: "shubhamdadwal/profile-website:01"
          ports:
            - containerPort: 3000